# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CricketNews' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod 'AFNetworking', '~> 2.6'
    pod 'PureLayout', '~> 3.0'
    pod 'SDWebImage', '~> 3.7'
    pod 'Reachability', '~> 3.2'
end
